# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ota_pb2 as ota__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ota_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FirmwareUpdateServiceStub(object):
    """The Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckForUpdate = channel.unary_unary(
                '/ota.FirmwareUpdateService/CheckForUpdate',
                request_serializer=ota__pb2.UpdateRequest.SerializeToString,
                response_deserializer=ota__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.DownloadUpdate = channel.unary_stream(
                '/ota.FirmwareUpdateService/DownloadUpdate',
                request_serializer=ota__pb2.DownloadRequest.SerializeToString,
                response_deserializer=ota__pb2.FileChunk.FromString,
                _registered_method=True)


class FirmwareUpdateServiceServicer(object):
    """The Service Definition
    """

    def CheckForUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FirmwareUpdateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckForUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckForUpdate,
                    request_deserializer=ota__pb2.UpdateRequest.FromString,
                    response_serializer=ota__pb2.UpdateResponse.SerializeToString,
            ),
            'DownloadUpdate': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadUpdate,
                    request_deserializer=ota__pb2.DownloadRequest.FromString,
                    response_serializer=ota__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ota.FirmwareUpdateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ota.FirmwareUpdateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FirmwareUpdateService(object):
    """The Service Definition
    """

    @staticmethod
    def CheckForUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ota.FirmwareUpdateService/CheckForUpdate',
            ota__pb2.UpdateRequest.SerializeToString,
            ota__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ota.FirmwareUpdateService/DownloadUpdate',
            ota__pb2.DownloadRequest.SerializeToString,
            ota__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
