# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ota.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ota.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tota.proto\x12\x03ota\";\n\rUpdateRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63urrent_version\x18\x02 \x01(\t\"\xe3\x01\n\x0eUpdateResponse\x12\x18\n\x10update_available\x18\x01 \x01(\x08\x12\x13\n\x0bnew_version\x18\x02 \x01(\t\x12\x15\n\rrelease_notes\x18\x03 \x01(\t\x12\x17\n\x0f\x66irmware_sha256\x18\x04 \x01(\t\x12\x1a\n\x12\x66irmware_signature\x18\x05 \x01(\t\x12.\n\x08severity\x18\x06 \x01(\x0e\x32\x1c.ota.UpdateResponse.Severity\"&\n\x08Severity\x12\x0c\n\x08OPTIONAL\x10\x00\x12\x0c\n\x08\x43RITICAL\x10\x01\"V\n\x0f\x44ownloadRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x19\n\x11version_requested\x18\x02 \x01(\t\x12\x15\n\rresume_offset\x18\x03 \x01(\x04\".\n\tFileChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\x32\x8c\x01\n\x15\x46irmwareUpdateService\x12\x39\n\x0e\x43heckForUpdate\x12\x12.ota.UpdateRequest\x1a\x13.ota.UpdateResponse\x12\x38\n\x0e\x44ownloadUpdate\x12\x14.ota.DownloadRequest\x1a\x0e.ota.FileChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ota_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEREQUEST']._serialized_start=18
  _globals['_UPDATEREQUEST']._serialized_end=77
  _globals['_UPDATERESPONSE']._serialized_start=80
  _globals['_UPDATERESPONSE']._serialized_end=307
  _globals['_UPDATERESPONSE_SEVERITY']._serialized_start=269
  _globals['_UPDATERESPONSE_SEVERITY']._serialized_end=307
  _globals['_DOWNLOADREQUEST']._serialized_start=309
  _globals['_DOWNLOADREQUEST']._serialized_end=395
  _globals['_FILECHUNK']._serialized_start=397
  _globals['_FILECHUNK']._serialized_end=443
  _globals['_FIRMWAREUPDATESERVICE']._serialized_start=446
  _globals['_FIRMWAREUPDATESERVICE']._serialized_end=586
# @@protoc_insertion_point(module_scope)
